// GENERATED FILE -- do not hand-edit.
// Source: vendor/oh-my-pi/packages/tui/src/theme/{dark,light}.json, symbols.ts
// Regenerate: npm run generate:omp-theme
// Verify: npm run generate:omp-theme:check

export const OMP_DARK_TOKENS: Readonly<Record<string, string | number>> = {
  "accent": "#febc38",
  "border": "#178fb9",
  "borderAccent": "#0088fa",
  "borderMuted": "#3d424a",
  "success": "#89d281",
  "error": "#fc3a4b",
  "warning": "#e4c00f",
  "muted": "#777d88",
  "dim": "#5f6673",
  "text": "",
  "thinkingText": "#777d88",
  "selectedBg": "#31363f",
  "userMessageBg": "#221d1a",
  "userMessageText": "",
  "customMessageBg": "#2a2530",
  "customMessageText": "",
  "customMessageLabel": "#b281d6",
  "toolPendingBg": "#1d2129",
  "toolSuccessBg": "#161a1f",
  "toolErrorBg": "#291d1d",
  "toolTitle": "",
  "toolOutput": "#777d88",
  "mdHeading": "#febc38",
  "mdLink": "#0088fa",
  "mdLinkUrl": "#5f6673",
  "mdCode": "#e5c1ff",
  "mdCodeBlock": "#9CDCFE",
  "mdCodeBlockBorder": "#777d88",
  "mdQuote": "#777d88",
  "mdQuoteBorder": "#3d424a",
  "mdHr": "#3d424a",
  "mdListBullet": "#febc38",
  "toolDiffAdded": "#89d281",
  "toolDiffRemoved": "#fc3a4b",
  "toolDiffContext": "#777d88",
  "link": "#0088fa",
  "syntaxComment": "#6A9955",
  "syntaxKeyword": "#569CD6",
  "syntaxFunction": "#DCDCAA",
  "syntaxVariable": "#9CDCFE",
  "syntaxString": "#CE9178",
  "syntaxNumber": "#B5CEA8",
  "syntaxType": "#4EC9B0",
  "syntaxOperator": "#D4D4D4",
  "syntaxPunctuation": "#D4D4D4",
  "thinkingOff": "#3d424a",
  "thinkingMinimal": "#5f6673",
  "thinkingLow": "#178fb9",
  "thinkingMedium": "#0088fa",
  "thinkingHigh": "#b281d6",
  "thinkingXhigh": "#e5c1ff",
  "bashMode": "#0088fa",
  "statusLineBg": "#121212",
  "statusLineSep": 244,
  "statusLineModel": "#d787af",
  "statusLinePath": "#00afaf",
  "statusLineGitClean": "#5faf5f",
  "statusLineGitDirty": "#d7af5f",
  "statusLineContext": "#8787af",
  "statusLineSpend": "#5fafaf",
  "statusLineStaged": 70,
  "statusLineDirty": 178,
  "statusLineUntracked": 39,
  "statusLineOutput": 205,
  "statusLineCost": 205,
  "statusLineSubagents": "#febc38",
  "pythonMode": "#e4c00f",
} as const;

export const OMP_LIGHT_TOKENS: Readonly<Record<string, string | number>> = {
  "accent": "#5a8080",
  "border": "#547da7",
  "borderAccent": "#5a8080",
  "borderMuted": "#b0b0b0",
  "success": "#588458",
  "error": "#aa5555",
  "warning": "#9a7326",
  "muted": "#6c6c6c",
  "dim": "#767676",
  "text": "",
  "thinkingText": "#6c6c6c",
  "selectedBg": "#d0d0e0",
  "userMessageBg": "#e8e8e8",
  "userMessageText": "",
  "customMessageBg": "#ede7f6",
  "customMessageText": "",
  "customMessageLabel": "#7e57c2",
  "toolPendingBg": "#e8e8f0",
  "toolSuccessBg": "#e8f0e8",
  "toolErrorBg": "#f0e8e8",
  "toolTitle": "",
  "toolOutput": "#6c6c6c",
  "mdHeading": "#9a7326",
  "mdLink": "#547da7",
  "mdLinkUrl": "#767676",
  "mdCode": "#5a8080",
  "mdCodeBlock": "#588458",
  "mdCodeBlockBorder": "#6c6c6c",
  "mdQuote": "#6c6c6c",
  "mdQuoteBorder": "#6c6c6c",
  "mdHr": "#6c6c6c",
  "mdListBullet": "#588458",
  "toolDiffAdded": "#588458",
  "toolDiffRemoved": "#aa5555",
  "toolDiffContext": "#6c6c6c",
  "syntaxComment": "#008000",
  "syntaxKeyword": "#0000FF",
  "syntaxFunction": "#795E26",
  "syntaxVariable": "#001080",
  "syntaxString": "#A31515",
  "syntaxNumber": "#098658",
  "syntaxType": "#267F99",
  "syntaxOperator": "#000000",
  "syntaxPunctuation": "#000000",
  "thinkingOff": "#b0b0b0",
  "thinkingMinimal": "#767676",
  "thinkingLow": "#547da7",
  "thinkingMedium": "#5a8080",
  "thinkingHigh": "#875f87",
  "thinkingXhigh": "#8b008b",
  "bashMode": "#588458",
  "statusLineBg": "#e0e0e0",
  "statusLineSep": "#808080",
  "statusLineModel": "#875f87",
  "statusLinePath": "#005f87",
  "statusLineGitClean": "#005f00",
  "statusLineGitDirty": "#af5f00",
  "statusLineContext": "#5f5f87",
  "statusLineSpend": "#005f5f",
  "statusLineStaged": 28,
  "statusLineDirty": 136,
  "statusLineUntracked": 31,
  "statusLineOutput": 133,
  "statusLineCost": 133,
  "statusLineSubagents": "#5a8080",
  "pythonMode": "#9a7326",
} as const;

export const OMP_DARK_EXPORT_TOKENS: Readonly<Record<"pageBg" | "cardBg", string>> = {
  "pageBg": "#18181e",
  "cardBg": "#1e1e24",
} as const;

export const OMP_LIGHT_EXPORT_TOKENS: Readonly<Record<"pageBg" | "cardBg", string>> = {
  "pageBg": "#f8f8f8",
  "cardBg": "#ffffff",
} as const;

export const OMP_SYMBOLS = {
  "unicode": {
    "status": {
      "success": "✔",
      "error": "✘",
      "warning": "⚠",
      "info": "ⓘ",
      "pending": "⏳",
      "disabled": "⦸",
      "enabled": "●",
      "running": "⟳",
      "shadowed": "○",
      "aborted": "⏹",
      "done": "•",
    },
    "nav": {
      "cursor": "❯",
      "selected": "➤",
      "expand": "▸",
      "collapse": "▾",
      "back": "⟵",
    },
    "tree": {
      "branch": "├─",
      "last": "└─",
      "vertical": "│",
      "horizontal": "─",
      "hook": "└",
    },
    "progress": {
      "filled": "━",
      "empty": "─",
    },
    "context": {
      "speculation": "╎",
      "compaction": "┃",
    },
    "boxRound": {
      "topLeft": "╭",
      "topRight": "╮",
      "bottomLeft": "╰",
      "bottomRight": "╯",
      "horizontal": "─",
      "vertical": "│",
    },
    "boxDotted": {
      "horizontal": "┄",
      "vertical": "┆",
    },
    "boxSharp": {
      "topLeft": "┌",
      "topRight": "┐",
      "bottomLeft": "└",
      "bottomRight": "┘",
      "horizontal": "─",
      "vertical": "│",
      "cross": "┼",
      "teeDown": "┬",
      "teeUp": "┴",
      "teeRight": "├",
      "teeLeft": "┤",
    },
    "sep": {
      "powerline": "▕",
      "powerlineThin": "┆",
      "powerlineLeft": "▶",
      "powerlineRight": "◀",
      "powerlineThinLeft": ">",
      "powerlineThinRight": "<",
      "powerlineCapLeft": "",
      "block": "▌",
      "space": " ",
      "asciiLeft": ">",
      "asciiRight": "<",
      "dot": " · ",
      "slash": " / ",
      "pipe": " │ ",
    },
    "icon": {
      "model": "⬢",
      "plan": "🗺",
      "prewalk": "🏃",
      "goal": "🎯",
      "pause": "⏸",
      "loop": "↻",
      "folder": "📁",
      "worktree": "🌳",
      "search": "🔍",
      "scratchFolder": "🗑",
      "file": "📄",
      "git": "⎇",
      "branch": "⑂",
      "pr": "⤴",
      "pin": "📌",
      "tokens": "🪙",
      "context": "◫",
      "cost": "💲",
      "subscription": "(sub)",
      "advisor": "👁",
      "advisorClosed": "🙈",
      "time": "⏱",
      "omp": "π",
      "esc": "⎋",
      "ghost": "👻",
      "agents": "👥",
      "job": "⚙",
      "cache": "💾",
      "cacheMiss": "⊘",
      "input": "⤵",
      "output": "⤴",
      "throughput": "⚡",
      "intelligence": "🧠",
      "host": "🖥",
      "session": "🆔",
      "package": "📦",
      "warning": "⚠",
      "rewind": "↶",
      "auto": "⟲",
      "fast": "⚡",
      "extensionSkill": "✦",
      "extensionTool": "🛠",
      "extensionSlashCommand": "⌘",
      "extensionMcp": "🔌",
      "extensionRule": "⚖",
      "extensionHook": "🪝",
      "extensionPrompt": "✎",
      "extensionContextFile": "📎",
      "extensionInstruction": "📘",
      "vimNormal": "■",
      "vimInsert": "▎",
      "vimVisual": "◉",
      "vimVisualLine": "≡",
      "mic": "🎤",
      "camera": "📷",
    },
    "cmd": {
      "action": "❯",
      "prompt": "✎",
      "extension": "🧩",
      "settings": "🎛",
      "gear": "⚙",
      "shield": "🛡",
      "wave": "∿",
      "compass": "🧭",
      "inbox": "📥",
      "swap": "⇄",
      "expand": "⤢",
      "computer": "🖥",
      "eye": "👁",
      "todo": "☑",
      "stats": "📊",
      "news": "📰",
      "keyboard": "⌨",
      "export": "📤",
      "clipboard": "📋",
      "share": "↗",
      "broadcast": "📡",
      "globe": "🌐",
      "copy": "⧉",
      "plus": "✚",
      "restart": "↻",
      "eraser": "🧹",
      "trash": "🗑",
      "compress": "🗜",
      "vibrate": "📳",
      "handoff": "➦",
      "history": "🕘",
      "question": "❓",
      "rocket": "🚀",
      "stethoscope": "🩺",
      "redo": "🔁",
      "bug": "🐛",
      "memory": "🧠",
      "pencil": "✏",
      "folderMove": "📂",
      "folderPlus": "📁",
      "folderMinus": "📁",
      "hammer": "🔨",
      "power": "⏻",
      "cart": "🛒",
    },
    "thinking": {
      "minimal": "○ min",
      "low": "◔ low",
      "medium": "◑ med",
      "high": "◒ high",
      "xhigh": "◕ xhigh",
      "max": "◉ max",
      "autoPending": "⟳",
    },
    "checkbox": {
      "checked": "☑",
      "unchecked": "☐",
    },
    "radio": {
      "selected": "◉",
      "unselected": "○",
    },
    "format": {
      "bullet": "•",
      "dash": "—",
      "bracketLeft": "⟦",
      "bracketRight": "⟧",
    },
    "md": {
      "quoteBorder": "▏",
      "hrChar": "─",
      "bullet": "•",
      "colorSwatch": "■",
    },
    "advisor": {
      "rail": "▎",
    },
    "skill": {
      "rail": "▎",
    },
    "lang": {
      "default": "⌘",
      "typescript": "🟦",
      "javascript": "🟨",
      "python": "🐍",
      "rust": "🦀",
      "go": "🐹",
      "java": "☕",
      "c": "Ⓒ",
      "cpp": "➕",
      "csharp": "♯",
      "ruby": "💎",
      "julia": "Ⓙ",
      "php": "🐘",
      "swift": "🕊",
      "kotlin": "🅺",
      "shell": "💻",
      "html": "🌐",
      "css": "🎨",
      "json": "🧾",
      "yaml": "📋",
      "markdown": "📝",
      "sql": "🗄",
      "docker": "🐳",
      "lua": "🌙",
      "text": "🗒",
      "env": "🔧",
      "toml": "🧾",
      "xml": "⟨⟩",
      "ini": "⚙",
      "conf": "⚙",
      "log": "📜",
      "csv": "📑",
      "tsv": "📑",
      "image": "🖼",
      "pdf": "📕",
      "archive": "🗜",
      "binary": "⚙",
    },
    "chip": {
      "image": "🖼",
      "video": "🎞",
      "paste": "📄",
    },
    "tab": {
      "appearance": "🎨",
      "model": "🤖",
      "interaction": "⌨",
      "context": "📋",
      "files": "📁",
      "shell": "💻",
      "tools": "🔧",
      "memory": "🧠",
      "tasks": "📦",
      "providers": "🌐",
    },
    "tool": {
      "write": "✎",
      "edit": "✎",
      "bash": "❯",
      "ssh": "⇄",
      "lsp": "💡",
      "gh": "⎇",
      "webSearch": "⌕",
      "exa": "🔭",
      "browser": "🌐",
      "eval": "▶",
      "debug": "🐞",
      "mcp": "🔌",
      "job": "⚙",
      "launch": "🚀",
      "task": "⇶",
      "todo": "☑",
      "memory": "🧠",
      "ask": "?",
      "resolve": "✓",
      "review": "◉",
      "goal": "◎",
      "irc": "✉",
      "delete": "🗑",
      "move": "➜",
    },
  },
  "nerd": {
    "status": {
      "success": "",
      "error": "",
      "warning": "",
      "info": "",
      "pending": "",
      "disabled": "",
      "enabled": "",
      "running": "",
      "shadowed": "",
      "aborted": "",
      "done": "•",
    },
    "nav": {
      "cursor": "",
      "selected": "",
      "expand": "",
      "collapse": "",
      "back": "",
    },
    "tree": {
      "branch": "├─",
      "last": "└─",
      "vertical": "│",
      "horizontal": "─",
      "hook": "└",
    },
    "progress": {
      "filled": "━",
      "empty": "─",
    },
    "context": {
      "speculation": "󰕝",
      "compaction": "󰁨",
    },
    "boxRound": {
      "topLeft": "╭",
      "topRight": "╮",
      "bottomLeft": "╰",
      "bottomRight": "╯",
      "horizontal": "─",
      "vertical": "│",
    },
    "boxDotted": {
      "horizontal": "┄",
      "vertical": "┆",
    },
    "boxSharp": {
      "topLeft": "┌",
      "topRight": "┐",
      "bottomLeft": "└",
      "bottomRight": "┘",
      "horizontal": "─",
      "vertical": "│",
      "cross": "┼",
      "teeDown": "┬",
      "teeUp": "┴",
      "teeRight": "├",
      "teeLeft": "┤",
    },
    "sep": {
      "powerline": "",
      "powerlineThin": "",
      "powerlineLeft": "",
      "powerlineRight": "",
      "powerlineThinLeft": "",
      "powerlineThinRight": "",
      "powerlineCapLeft": "",
      "block": "█",
      "space": " ",
      "asciiLeft": ">",
      "asciiRight": "<",
      "dot": " · ",
      "slash": "",
      "pipe": "",
    },
    "icon": {
      "model": "",
      "plan": "",
      "prewalk": "",
      "goal": "",
      "pause": "",
      "loop": "",
      "folder": "",
      "search": "",
      "scratchFolder": "",
      "worktree": "",
      "file": "",
      "git": "",
      "branch": "",
      "pr": "",
      "pin": "",
      "tokens": "",
      "context": "",
      "cost": "",
      "subscription": "󰙺",
      "advisor": "",
      "advisorClosed": "",
      "time": "",
      "omp": "󰵗",
      "esc": "󱊷",
      "ghost": "󰊠",
      "agents": "",
      "job": "",
      "cache": "",
      "cacheMiss": "",
      "input": "",
      "output": "",
      "throughput": "",
      "intelligence": "",
      "host": "",
      "session": "󰁑",
      "package": "",
      "warning": "",
      "rewind": "",
      "auto": "󰁨",
      "fast": "",
      "extensionSkill": "",
      "extensionTool": "",
      "extensionSlashCommand": "",
      "extensionMcp": "",
      "extensionRule": "",
      "extensionHook": "",
      "extensionPrompt": "",
      "extensionContextFile": "",
      "extensionInstruction": "",
      "vimNormal": "",
      "vimInsert": "",
      "vimVisual": "",
      "vimVisualLine": "",
      "mic": "",
      "camera": "",
    },
    "cmd": {
      "action": "",
      "prompt": "󰺫",
      "extension": "",
      "settings": "",
      "gear": "",
      "shield": "",
      "wave": "󰥛",
      "compass": "",
      "inbox": "",
      "swap": "󰓡",
      "expand": "󰁌",
      "computer": "",
      "eye": "",
      "todo": "",
      "stats": "",
      "news": "",
      "keyboard": "",
      "export": "",
      "clipboard": "",
      "share": "",
      "broadcast": "",
      "globe": "",
      "copy": "",
      "plus": "",
      "restart": "󰜉",
      "eraser": "",
      "trash": "",
      "compress": "",
      "vibrate": "󰕦",
      "handoff": "",
      "history": "󰋚",
      "question": "",
      "rocket": "",
      "stethoscope": "",
      "redo": "󰑎",
      "bug": "",
      "memory": "󰍛",
      "pencil": "",
      "folderMove": "󰉒",
      "folderPlus": "󰉗",
      "folderMinus": "󰉘",
      "hammer": "󰣪",
      "power": "",
      "cart": "",
    },
    "thinking": {
      "minimal": "󰪞 min",
      "low": "󰪟 low",
      "medium": "󰪡 med",
      "high": "󰪣 high",
      "xhigh": "󰪥 xhi",
      "max": " max",
      "autoPending": "",
    },
    "checkbox": {
      "checked": "",
      "unchecked": "",
    },
    "radio": {
      "selected": "",
      "unselected": "",
    },
    "format": {
      "bullet": "",
      "dash": "–",
      "bracketLeft": "⟨",
      "bracketRight": "⟩",
    },
    "md": {
      "quoteBorder": "│",
      "hrChar": "─",
      "bullet": "",
      "colorSwatch": "■",
    },
    "advisor": {
      "rail": "▎",
    },
    "skill": {
      "rail": "▎",
    },
    "lang": {
      "default": "",
      "typescript": "",
      "javascript": "",
      "python": "",
      "rust": "",
      "go": "",
      "java": "",
      "c": "",
      "cpp": "",
      "csharp": "",
      "ruby": "",
      "julia": "",
      "php": "",
      "swift": "",
      "kotlin": "",
      "shell": "",
      "html": "",
      "css": "",
      "json": "",
      "yaml": "",
      "markdown": "",
      "sql": "",
      "docker": "",
      "lua": "",
      "text": "",
      "env": "",
      "toml": "",
      "xml": "󰗀",
      "ini": "",
      "conf": "",
      "log": "󰌱",
      "csv": "󰈛",
      "tsv": "󰈛",
      "image": "󰈟",
      "pdf": "󰈦",
      "archive": "",
      "binary": "󰆚",
    },
    "chip": {
      "image": "",
      "video": "",
      "paste": "",
    },
    "tab": {
      "appearance": "󰃣",
      "model": "󰚩",
      "interaction": "󰌌",
      "context": "󰘸",
      "files": "󰈔",
      "shell": "󰆍",
      "tools": "󰠭",
      "memory": "󰧑",
      "tasks": "󰐱",
      "providers": "󰖟",
    },
    "tool": {
      "write": "",
      "edit": "",
      "bash": "",
      "ssh": "",
      "lsp": "",
      "gh": "",
      "webSearch": "",
      "exa": "",
      "browser": "",
      "eval": "",
      "debug": "",
      "mcp": "",
      "job": "",
      "launch": "",
      "task": "",
      "todo": "",
      "memory": "",
      "ask": "",
      "resolve": "",
      "review": "",
      "goal": "",
      "irc": "",
      "delete": "",
      "move": "",
    },
  },
  "ascii": {
    "status": {
      "success": "[ok]",
      "error": "[!!]",
      "warning": "[!]",
      "info": "[i]",
      "pending": "[*]",
      "disabled": "[ ]",
      "enabled": "[x]",
      "running": "[~]",
      "shadowed": "[/]",
      "aborted": "[-]",
      "done": "*",
    },
    "nav": {
      "cursor": ">",
      "selected": "->",
      "expand": "+",
      "collapse": "-",
      "back": "<-",
    },
    "tree": {
      "branch": "|--",
      "last": "'--",
      "vertical": "|",
      "horizontal": "-",
      "hook": "`-",
    },
    "progress": {
      "filled": "=",
      "empty": "-",
    },
    "context": {
      "speculation": ":",
      "compaction": "|",
    },
    "boxRound": {
      "topLeft": "+",
      "topRight": "+",
      "bottomLeft": "+",
      "bottomRight": "+",
      "horizontal": "-",
      "vertical": "|",
    },
    "boxDotted": {
      "horizontal": "-",
      "vertical": ":",
    },
    "boxSharp": {
      "topLeft": "+",
      "topRight": "+",
      "bottomLeft": "+",
      "bottomRight": "+",
      "horizontal": "-",
      "vertical": "|",
      "cross": "+",
      "teeDown": "+",
      "teeUp": "+",
      "teeRight": "+",
      "teeLeft": "+",
    },
    "sep": {
      "powerline": ">",
      "powerlineThin": ">",
      "powerlineLeft": ">",
      "powerlineRight": "<",
      "powerlineThinLeft": ">",
      "powerlineThinRight": "<",
      "powerlineCapLeft": "",
      "block": "#",
      "space": " ",
      "asciiLeft": ">",
      "asciiRight": "<",
      "dot": " - ",
      "slash": " / ",
      "pipe": " | ",
    },
    "icon": {
      "model": "[M]",
      "plan": "plan",
      "prewalk": "prewalk",
      "goal": "goal",
      "pause": "||",
      "loop": "loop",
      "folder": "[D]",
      "worktree": "[wt]",
      "search": "[/]",
      "scratchFolder": "[T]",
      "file": "[F]",
      "git": "git:",
      "branch": "@",
      "pr": "PR",
      "pin": "*",
      "tokens": "tok:",
      "context": "ctx:",
      "cost": "$",
      "subscription": "(sub)",
      "advisor": "(adv)",
      "advisorClosed": "(adv)",
      "time": "t:",
      "omp": "pi",
      "esc": "esc",
      "ghost": "@",
      "agents": "AG",
      "job": "bg",
      "output": "out:",
      "throughput": "tok/s:",
      "intelligence": "IQ",
      "cache": "cache",
      "cacheMiss": "!",
      "input": "in:",
      "host": "host",
      "session": "id",
      "package": "[P]",
      "warning": "[!]",
      "rewind": "<-",
      "auto": "[A]",
      "fast": ">>",
      "extensionSkill": "SK",
      "extensionTool": "TL",
      "extensionSlashCommand": "/",
      "extensionMcp": "MCP",
      "extensionRule": "RL",
      "extensionHook": "HK",
      "extensionPrompt": "PR",
      "extensionContextFile": "CF",
      "extensionInstruction": "IN",
      "vimNormal": "N",
      "vimInsert": "I",
      "vimVisual": "V",
      "vimVisualLine": "L",
      "mic": "MIC",
      "camera": "[o]",
    },
    "cmd": {
      "action": "",
      "prompt": "",
      "extension": "",
      "settings": "",
      "gear": "",
      "shield": "",
      "wave": "",
      "compass": "",
      "inbox": "",
      "swap": "",
      "expand": "",
      "computer": "",
      "eye": "",
      "todo": "",
      "stats": "",
      "news": "",
      "keyboard": "",
      "export": "",
      "clipboard": "",
      "share": "",
      "broadcast": "",
      "globe": "",
      "copy": "",
      "plus": "",
      "restart": "",
      "eraser": "",
      "trash": "",
      "compress": "",
      "vibrate": "",
      "handoff": "",
      "history": "",
      "question": "",
      "rocket": "",
      "stethoscope": "",
      "redo": "",
      "bug": "",
      "memory": "",
      "pencil": "",
      "folderMove": "",
      "folderPlus": "",
      "folderMinus": "",
      "hammer": "",
      "power": "",
      "cart": "",
    },
    "thinking": {
      "minimal": "[min]",
      "low": "[low]",
      "medium": "[med]",
      "high": "[high]",
      "xhigh": "[xhi]",
      "max": "[max]",
      "autoPending": "[~]",
    },
    "checkbox": {
      "checked": "[x]",
      "unchecked": "[ ]",
    },
    "radio": {
      "selected": "(o)",
      "unselected": "( )",
    },
    "format": {
      "bullet": "*",
      "dash": "-",
      "bracketLeft": "[",
      "bracketRight": "]",
    },
    "md": {
      "quoteBorder": "|",
      "hrChar": "-",
      "bullet": "*",
      "colorSwatch": "[]",
    },
    "advisor": {
      "rail": "|",
    },
    "skill": {
      "rail": "|",
    },
    "lang": {
      "default": "code",
      "typescript": "ts",
      "javascript": "js",
      "python": "py",
      "rust": "rs",
      "go": "go",
      "java": "java",
      "c": "c",
      "cpp": "cpp",
      "csharp": "cs",
      "ruby": "rb",
      "julia": "jl",
      "php": "php",
      "swift": "swift",
      "kotlin": "kt",
      "shell": "sh",
      "html": "html",
      "css": "css",
      "json": "json",
      "yaml": "yaml",
      "markdown": "md",
      "sql": "sql",
      "docker": "docker",
      "lua": "lua",
      "text": "txt",
      "env": "env",
      "toml": "toml",
      "xml": "xml",
      "ini": "ini",
      "conf": "conf",
      "log": "log",
      "csv": "csv",
      "tsv": "tsv",
      "image": "img",
      "pdf": "pdf",
      "archive": "zip",
      "binary": "bin",
    },
    "chip": {
      "image": "img",
      "video": "vid",
      "paste": "txt",
    },
    "tab": {
      "appearance": "[A]",
      "model": "[M]",
      "interaction": "[I]",
      "context": "[X]",
      "files": "[F]",
      "shell": "[S]",
      "tools": "[T]",
      "memory": "[Y]",
      "tasks": "[K]",
      "providers": "[P]",
    },
    "tool": {
      "write": "+f",
      "edit": "~",
      "bash": "$",
      "ssh": "ssh",
      "lsp": "lsp",
      "gh": "gh",
      "webSearch": "web",
      "exa": "exa",
      "browser": "[w]",
      "eval": ">_",
      "debug": "dbg",
      "mcp": "<>",
      "job": "job",
      "launch": "run",
      "task": ">>>",
      "todo": "[x]",
      "memory": "mem",
      "ask": "[?]",
      "resolve": "[v]",
      "review": "rev",
      "goal": "(o)",
      "irc": "#",
      "delete": "rm",
      "move": "mv",
    },
  },
} as const;

export const OMP_SPINNER_FRAMES: Readonly<Record<"unicode" | "nerd" | "ascii", Readonly<Record<"status" | "activity", readonly string[]>>>> = {
  "unicode": {
    "status": [
      "⣾",
      "⣽",
      "⣻",
      "⢿",
      "⡿",
      "⣟",
      "⣯",
      "⣷",
    ],
    "activity": [
      "⠋",
      "⠙",
      "⠹",
      "⠸",
      "⠼",
      "⠴",
      "⠦",
      "⠧",
      "⠇",
      "⠏",
    ],
  },
  "nerd": {
    "status": [
      "󱑖",
      "󱑋",
      "󱑌",
      "󱑍",
      "󱑎",
      "󱑏",
      "󱑐",
      "󱑑",
      "󱑒",
      "󱑓",
      "󱑔",
      "󱑕",
    ],
    "activity": [
      "⠋",
      "⠙",
      "⠹",
      "⠸",
      "⠼",
      "⠴",
      "⠦",
      "⠧",
      "⠇",
      "⠏",
    ],
  },
  "ascii": {
    "status": [
      "|",
      "/",
      "-",
      "\\",
    ],
    "activity": [
      "-",
      "\\",
      "|",
      "/",
    ],
  },
} as const;
